### ISSUE TITLE
Deletion failed, path = '/private/tmp/pub_d977xM' (OS Error: Too many open files

### ISSUE THREAD

**Issue by jingkeling** [leoafarias/homebrew-fvm#11]
```
➜  ~ brew install fvm
==> Fetching leoafarias/fvm/fvm
==> Downloading https://github.com/fluttertools/fvm/archive/2.4.1.tar.gz
Already downloaded: /Users/xxx/Library/Caches/Homebrew/downloads/54b77538c3b1241d7203cf322d4c29f344917cfacab6f1f19203cff6dc2390e4--fvm-2.4.1.tar.gz
==> Installing fvm from leoafarias/fvm
==> /opt/homebrew/opt/dart/libexec/bin/dart pub get
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/fvm/01.dart:
2023-05-10 07:01:10 +0000

/opt/homebrew/opt/dart/libexec/bin/dart
pub
get

Resolving dependencies...
Deletion failed, path = '/private/tmp/pub_d977xM' (OS Error: Too many open files, errno = 24)
```

Mac mini M2 Pro
macos Ventura 13.3.1 (a)

**Comment by xqm32** [comment]
I have the same problem.
MacBook Air with M2
macOS 13.4 (22F66)

**Comment by xqm32** [comment]
> I have the same problem
> 
> MacBook Air with M2 macOS 13.4 (22F66)
> 
> ```
> ==> Fetching leoafarias/fvm/fvm
> ==> Downloading https://github.com/fluttertools/fvm/archive/2.4.1.tar.gz
> Already downloaded: /Users/xqm/Library/Caches/Homebrew/downloads/54b77538c3b1241d7203cf322d4c29f344917cfacab6f1f19203cff6dc2390e4--fvm-2.4.1.tar.gz
> ==> Installing fvm from leoafarias/fvm
> ==> /opt/homebrew/opt/dart/libexec/bin/dart pub get
> Last 15 lines from /Users/xqm/Library/Logs/Homebrew/fvm/01.dart:
> 2023-06-14 08:14:50 +0000
> 
> /opt/homebrew/opt/dart/libexec/bin/dart
> pub
> get
> 
> Resolving dependencies...
> Deletion failed, path = '/private/tmp/pub_mJFTN8' (OS Error: Too many open files, errno = 24)
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
>   https://github.com/leoafarias/homebrew-fvm/issues
> ```

I switched to a faster net and now there is no problem. It appears to be a network issue.

**Comment by yaotiancheng-ola** [comment]
same error, is fixed?

**Comment by aboutlan** [comment]
The same problem and solved by switching to another wifi.

**Comment by leoafarias** [comment]
@yaotiancheng-ola thanks, it seems is not fvm specific.
