### ISSUE TITLE
Can't install fvm by brew

### ISSUE THREAD

**Issue by mbojec** [leoafarias/homebrew-fvm#16]
Hi, I wanted to install fem with brew and below I adding the error message (to low dart-lang version)

~ % brew install leoafarias/fvm/fvm      
==> Fetching dependencies for leoafarias/fvm/fvm: dart-lang/dart/dart
==> Fetching dart-lang/dart/dart
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/rele
Already downloaded: /Users/marek/Library/Caches/Homebrew/downloads/bc5aa44d374fc4d2e130a4c01da40d02aa67be65fd995b089df8dfdbaad2288c--dartsdk-macos-arm64-release.zip
==> Fetching leoafarias/fvm/fvm
==> Downloading https://github.com/leoafarias/fvm/archive/3.0.0.tar.gz
Already downloaded: /Users/marek/Library/Caches/Homebrew/downloads/e959c575d757d1d5793de1f67d223a614b66dec3b0b9bd88f64660c27262c991--fvm-3.0.0.tar.gz
==> Installing fvm from leoafarias/fvm
==> Installing dependencies for leoafarias/fvm/fvm: dart-lang/dart/dart
==> Installing leoafarias/fvm/fvm dependency: dart-lang/dart/dart
🍺  /opt/homebrew/Cellar/dart/2.16.1: 869 files, 491.4MB, built in 5 seconds
==> Installing leoafarias/fvm/fvm
==> /opt/homebrew/opt/dart/libexec/bin/dart pub get
Last 15 lines from /Users/marek/Library/Logs/Homebrew/fvm/01.dart:
2024-02-11 16:05:50 +0000

/opt/homebrew/opt/dart/libexec/bin/dart
pub
get

Resolving dependencies...
The current Dart SDK version is 2.16.1.

Because fvm requires SDK version >=2.17.0 <4.0.0, version solving failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/leoafarias/homebrew-fvm/issues

These open issues may also help:
leoafarias/fvm/fvm 2.4.1 did not build https://github.com/leoafarias/homebrew-fvm/issues/15
fvm relying on an older version of dart and failing via brew install https://github.com/leoafarias/homebrew-fvm/issues/14

**Comment by leoafarias** [comment]
The issue, I believe, is because it is using the cached stable version you had last time.

Is there a way to force the install and/or clear the cache path for the SDK in your output?

**Comment by mbojec** [comment]
I have deleted Dart before running brew install fvm and still receive this error. I have albo tried to install flutter directly so that I have Dart version 3.2 and it also didn't helped. 

I also tried to install fvm 2.4.1 because I have this version on my other computer but I get info that there is no such version (yet on that other machine I have it)

**Comment by limajr** [comment]
Possibly the solution is to change the dependency in "dart" to be "dart-sdk" in brew. That is at least a bit updated.

**Comment by leoafarias** [comment]
@mbojec just to be clear I mean running this command here to remove the cache.

```bash
rm /Users/marek/Library/Caches/Homebrew/downloads/bc5aa44d374fc4d2e130a4c01da40d02aa67be65fd995b089df8dfdbaad2288c--dartsdk-macos-arm64-release.zip
```

and then installing it again, I am just suspecting that the previous stable version is cached... if this fixes the issue I can improve the formula to always download the latest

**Comment by leoafarias** [comment]
@mbojec I have forced the sdk version of dart to compile the brew formula. Could you test this, to see if it resolves the issue?

**Comment by ranjithbobby89** [comment]
> @mbojec I have forced the sdk version of dart to compile the brew formula. Could you test this, to see if it resolves the issue? Just run the brew install again on fvm

No still we have an issue

**Comment by ranjithbobby89** [comment]
@leoafarias  

> Install fvm install.
==> Tapping homebrew/cask
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-cask'...
Tapped 4377 casks (4,451 files, 366.2MB).
Warning: No available formula with the name "fvm". Did you mean fnm, nvm, dvm or bvm?
==> Searching for similarly named formulae...

getting error on install fvm

**Comment by leoafarias** [comment]
So glad to hear this!! Thank you for helping through it!
