### ISSUE TITLE
/usr/local/opt/dart/bin/pub get has a problem

### ISSUE THREAD

**Issue by uxiume** [leoafarias/homebrew-fvm#2]
<img width="675" alt="WX20210507-073900@2x" src="https://user-images.githubusercontent.com/38536031/117378113-5a53b800-af07-11eb-8d9a-2d0ae65c287d.png">

**Comment by leoafarias** [comment]
Can you run this with a —verbose flag. Not sure what the error is.. maybe a timeout?

**Comment by uxiume** [comment]
if there don't need this tool , can you remove it ?
![image](https://user-images.githubusercontent.com/38536031/117406332-7ecb8680-af3f-11eb-9869-a3f77c65fa58.png)

**Comment by uxiume** [comment]
maybe, it's my computer problem, but it download very slow in China

**Comment by leoafarias** [comment]
@uxiume This is not a direct dependency, so its not as easy to remove. 

Also, did you try using the mirror pub server in china?

Set `PUB_HOSTED_URL` to be `https://pub.flutter-io.cn`

**Comment by yanglilizhang** [comment]
@uxiume 你的这个问题解决了没，我的也出现了这样的问题

**Comment by uxiume** [comment]
https://fvm.app/docs/getting_started/installation

打开上面这个网址，找到下面图上这一句代码，先把 flutter 安装好，更新到最新的稳定版，然后运行一下那个命令，很快就安装好了
<img width="1025" alt="WX20210512-155439@2x" src="https://user-images.githubusercontent.com/38536031/117939478-abfea700-b33a-11eb-8c82-0221e84800c4.png">

**Comment by uxiume** [comment]
@yanglilizhang 你试试刚刚上面这个方法

**Comment by uxiume** [comment]
@yanglilizhang 要不你直接加我微信，说一下怎么弄也可以 changzuibuxingzimeng

**Comment by yanglilizhang** [comment]
> @yanglilizhang 要不你直接加我微信，说一下怎么弄也可以 changzuibuxingzimeng

多谢

**Comment by yanglilizhang** [comment]
> @uxiume 多谢 我加下你

**Comment by leoafarias** [comment]
Seems like this has been solved, please reopen in case you have any problems.
