### ISSUE TITLE
failed to execute dart2native

### ISSUE THREAD

**Issue by spicydonuts** [leoafarias/homebrew-fvm#4]
`brew install fvm` results in the following error:

```
==> /usr/local/opt/dart/bin/dart2native -Dversion=2.2.4 bin/main.dart -o fvm
Failed to execute: /usr/local/opt/dart/bin/dart2native
```

`dart2native` doesn't exist in dart 2.15.0 (the one just installed by `brew install fvm`). [It looks like it was replaced](https://dart.dev/tools/dart-compile) by `dart compile`:
> The `dart compile` command replaces the `dart2native`, `dart2aot`, and `dart2js` commands.

**Comment by leoafarias** [comment]
@spicydonuts thanks for reporting this. Fixed it!
